{
 "title": "Web Metrics from nginx Logs",
 "tags": [
  "sre",
  "nginx",
  "${PRODUCT_REPLACE}",
  "${ENVIRONMENT_REPLACE}",
  "${PRODUCT_REPLACE}-${ENVIRONMENT_REPLACE}"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"} | logfmt | status!=\"\" | __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"} | logfmt | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"} | logfmt | status >= 500 |__error__=\"\"[$__interval])) / (sum(rate({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"} | logfmt | __error__=\"\"[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"}\n|=\"ingress\" !=\"stderr\"\n| logfmt [5m])) by (status)"
    }
   ]
  },
  {
   "title": "Only 4xx/5xx HTTP Requests by Application",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"}\n|=\"ingress\" !=\"stderr\"\n| logfmt\n| status!~\"[123].+\" [5m])) by (status, proxy_upstream_name)"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"} | logfmt | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "topk(20, sum by (true_client_ip) (count_over_time({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"} | logfmt | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | true_client_ip !~ \"35.236.203.238\" | true_client_ip !~ \"35.245.111.20\" | true_client_ip !~ \"34.145.190.143\" | true_client_ip !~ \"34.86.70.28\" | true_client_ip !~ \"34.86.56.199\" | true_client_ip !~ \"34.73.58.112\" | true_client_ip !~ \"35.185.47.116\" | true_client_ip !~ \"34.138.128.79\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/robots.txt\" |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{true_client_ip}}"
    }
   ]
  },
  {
   "title": "Top Requested Pages - Excluding '/'",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "topk(10,sum by (request_uri) (count_over_time({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"} | logfmt | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | request_uri != \"/\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  {
   "title": "Requests by Application",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"}\n|=\"ingress\" !=\"stderr\"\n| logfmt | proxy_upstream_name!=\"\" [5m])) by (proxy_upstream_name)"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Average BE Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "avg_over_time(\n{app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"}\n|=\"ingress\" !=\"stderr\"\n| logfmt\n| proxy_upstream_name=\"backend-consumer-graphql-api-web\"\n| unwrap upstream_response_time | __error__=\"\" [1m]) by (proxy_upstream_name)"
    }
   ]
  },
  {
   "title": "P99 Backend Response Time by Request URI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "quantile_over_time(0.99,\n{app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"}\n|=\"ingress\" !=\"stderr\"\n| logfmt\n| proxy_upstream_name=\"backend-consumer-graphql-api-web\"\n| request_uri!=\"/consumer/graphql?authorizePackNFTsMinting\"\n| unwrap upstream_response_time | __error__=\"\" [1m]) by (proxy_upstream_name, request_uri)"
    }
   ]
  },
  {
   "title": "Top BE URLs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "topk(10, sum(rate({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"}\n|=\"ingress\" !=\"stderr\"\n| logfmt | uri=~\"\\\\/api\\\\/.+\" [5m])) by (uri))"
    }
   ]
  },
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Average FE Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "avg_over_time(\n{app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"}\n|=\"ingress\" !=\"stderr\"\n| logfmt\n| proxy_upstream_name=\"frontend-nfl-app-v1-web\"\n| unwrap upstream_response_time | __error__=\"\" [1m]) by (proxy_upstream_name)"
    }
   ]
  },
  {
   "title": "P99 FE Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "quantile_over_time(0.99,\n{app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"}\n|=\"ingress\" !=\"stderr\"\n| logfmt\n| proxy_upstream_name=\"frontend-nfl-app-v1-web\"\n| unwrap upstream_response_time | __error__=\"\" [1m]) by (proxy_upstream_name)"
    }
   ]
  },
  {
   "title": "Top FE URLs excluding /, /_next/data and /api/",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "topk(10, sum(rate({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"}\n|=\"ingress\" !=\"stderr\"\n| logfmt | proxy_upstream_name=\"frontend-nfl-app-v1-web\" | uri!=\"/\" | uri!~\"\\\\/_next\\\\/data\\\\/.+\" | uri!~\"\\\\/api/.+\" [5m])) by (uri))"
    }
   ]
  },
  {
   "title": "Topk 10 FE Requests by URI",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "topk(10, sum(rate({app=\"${APP_NAME}\", env=\"${ENVIRONMENT_REPLACE}\"}\n|=\"ingress\" !=\"stderr\"\n| logfmt | proxy_upstream_name=\"frontend-nfl-app-v1-web\" | uri!=\"/api/flags\" [5m])) by (uri))"
    }
   ]
  }
 ]
}